API_BASE_URL_V2=https://apiv2-test.snapbizz.com/v2/api/
BASE_URL_V3=https://apiv2-test.snapbizz.com/v3/api/
FILE_UPLOAD_URL=https://api-sb-test.snapbizz.com
FILE_UPLOAD_BUCKET=snap-report-test
PORTAL_ENTERPRISE_DOWNSYNC_URL=https://retailer-portal-test.snapbizz.com:3002/api/v2/
BRAND_PORTAL_URL=https://brands-test.snapbizz.com/api/
BRAND_PORTAL_PAYBACK_URL=https://apiv2-test.snapbizz.com:8091/v2/pos/payback/
RETAILER_PORTAL_URL=https://admin-test.snapbizz.com/Retailer-Portal/api/
FORCE_SYNC_BASE_URL=https://apiv2-test.snapbizz.com
ENTERPRISE_DATA_REFINE_URL=https://retailer-portal-test.snapbizz.com:3013/api/
BRAND_DASHBOARD_URL=http://brands-dashboard-test.snapbizz.com/store-status?storeId=
SNAP_ORDER_URL=https://snaporder-api-test.snapbizz.com/api/
STORE_CHECK_PORTAL=https://retailer-portal-test.snapbizz.com:8001/api/v1/
ENTERPRISE_CLEAN_STATUS_URL=https://retailer-portal-test.snapbizz.com:3013/api/
ENTERPRISE_PLAN_URL=https://api-sb-test.snapbizz.com/v1/api/web/
SNAP_ORDER_IMAGE_UPLOAD_URL=https://snaporder-test.sgp1.digitaloceanspaces.com/uploads/
SNAP_IMAGE_URL=http://brands-dashboard-test.snapbizz.com:49159/image/
SNAP_IMAGE_HOST_URL=https://snapbizztestcidata.s3.ap-south-1.amazonaws.com
SNAP_IMAGE_CONTAINER=snapbizz-test
SNAP_ORDER_API_URL=https://snaporder-api-test.snapbizz.com/api/
STOCK_TRANSFER_URL=https://retailer-portal-test.snapbizz.com:8000/api/v2/stock-transfer/
STOCK_TRANSFER_STATUS_URL=https://retailer-portal-test.snapbizz.com:8000/api/v2/portal/stock-transfer/
FCM_REGISTER_TOKEN_URL=https://retailer-portal-test.snapbizz.com:3000/api/push-notification/
DISTRIBUTOR_PO_URL=https://retailer-portal-test.snapbizz.com:8000/api/v1/
STAMPEE_SYNC_BASE_URL=https://apiv2-test.snapbizz.com
SYNC_PORTAL_URL=https://retailer-portal-test.snapbizz.com:8000/api/v2/
SMS_BASE_URL_V3=https://api-sb-test.snapbizz.com/v1/api/
ICICI_UNIQUE_MERCHANT_URL=https://api-sb-test.snapbizz.com/
RETAILER_PORTAL=https://retailer-portal-test.snapbizz.com:3010/api/
CASHFREE_SERVER_BASE_URL=https://api-cashfree-test.snapbizz.com
LOYALTY_BASE_URL=https://api-sb-test.snapbizz.com
SUBSCRIPTION_BASE_URL_V2=https://apiv2-test.snapbizz.com/
